version: "3.9"
services:
  nginx:
    image: "nginx:stable-alpine3.17" # "{{ nginx_version }}"
    container_name: nginx
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "/root/nginx" # "{{ config_dir }}"
        target: "/etc/nginx/conf.d"
      - type: bind
        source: "/var/www/html" # "{{ html_dir }}"
        target: "/var/www/html"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
